language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - COMPOSER_ROOT_VERSION=dev-master composer update --no-interaction --prefer-dist
  - COMPOSER_ROOT_VERSION=dev-master composer require --dev codeclimate/php-test-reporter:dev-master

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=26818103eb39ba4338a28bf5979039214f6ad9443594c9f1813126c004f27cae ./vendor/bin/test-reporter